/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasModificadas;

import com.mycompany.tiendaropa.*;
import static com.mycompany.tiendaropa.VentanaIngreso.titulo;

/**
 *
 * @author User
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpRCliente = new javax.swing.JPanel();
        btCliente = new javax.swing.JButton();
        jpFactura = new javax.swing.JPanel();
        btFacCliente = new javax.swing.JButton();
        jpUsuario = new javax.swing.JPanel();
        btUsuario = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        btProductos = new javax.swing.JButton();
        jpProveedor = new javax.swing.JPanel();
        btProveedor = new javax.swing.JButton();
        jpCategoria = new javax.swing.JPanel();
        btCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Glamour Fusion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jpRCliente.setLayout(new java.awt.BorderLayout());

        btCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btCliente.setText("Registrar Cliente");
        btCliente.setContentAreaFilled(false);
        btCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpRCliente.add(btCliente, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpRCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 165, 45));

        jpFactura.setLayout(new java.awt.BorderLayout());

        btFacCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btFacCliente.setText("Generar Factura");
        btFacCliente.setContentAreaFilled(false);
        btFacCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpFactura.add(btFacCliente, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 165, 45));

        jpUsuario.setLayout(new java.awt.BorderLayout());

        btUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btUsuario.setText("Registrar Usuario");
        btUsuario.setContentAreaFilled(false);
        btUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpUsuario.add(btUsuario, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 165, 45));

        jpProductos.setLayout(new java.awt.BorderLayout());

        btProductos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btProductos.setText("Registrar Productos");
        btProductos.setContentAreaFilled(false);
        btProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpProductos.add(btProductos, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 165, 45));

        jpProveedor.setLayout(new java.awt.BorderLayout());

        btProveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btProveedor.setText("Factura de Proveedor");
        btProveedor.setContentAreaFilled(false);
        btProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpProveedor.add(btProveedor, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 165, 45));

        jpCategoria.setLayout(new java.awt.BorderLayout());

        btCategoria.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btCategoria.setText("Agregar Categoría");
        btCategoria.setContentAreaFilled(false);
        btCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpCategoria.add(btCategoria, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 165, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public void cerrarVentana(){
        this.dispose();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFacCliente;
    private javax.swing.JButton btProductos;
    private javax.swing.JButton btProveedor;
    private javax.swing.JButton btUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpCategoria;
    private javax.swing.JPanel jpFactura;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedor;
    private javax.swing.JPanel jpRCliente;
    private javax.swing.JPanel jpUsuario;
    // End of variables declaration//GEN-END:variables
}
