/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasRegistro;

import static VentanasRegistro.VentanaIngreso.titulo;
import java.awt.Color;

/**
 *
 * @author User
 */
public class VentanaMenu extends javax.swing.JFrame {
    Color btColorOscuro = new Color(40,110,133);
    Color btColor = new Color(62,169,204);
    /**
     * Creates new form NewJFrame
     */
    public VentanaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpRCliente = new javax.swing.JPanel();
        btCliente = new javax.swing.JButton();
        jpFactura = new javax.swing.JPanel();
        btFacCliente = new javax.swing.JButton();
        jpUsuario = new javax.swing.JPanel();
        btUsuario = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        btProductos = new javax.swing.JButton();
        jpProveedor = new javax.swing.JPanel();
        btProveedor = new javax.swing.JButton();
        jpCategoria = new javax.swing.JPanel();
        btCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Glamour Fusion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 40, 620, -1));

        jpRCliente.setBackground(new java.awt.Color(62, 169, 204));
        jpRCliente.setLayout(new java.awt.BorderLayout());

        btCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btCliente.setForeground(new java.awt.Color(255, 255, 255));
        btCliente.setText("Registrar Cliente");
        btCliente.setBorder(null);
        btCliente.setContentAreaFilled(false);
        btCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btClienteMouseExited(evt);
            }
        });
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        jpRCliente.add(btCliente, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpRCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 165, 45));

        jpFactura.setBackground(new java.awt.Color(62, 169, 204));
        jpFactura.setLayout(new java.awt.BorderLayout());

        btFacCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btFacCliente.setForeground(new java.awt.Color(255, 255, 255));
        btFacCliente.setText("Generar Factura");
        btFacCliente.setBorder(null);
        btFacCliente.setContentAreaFilled(false);
        btFacCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFacCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFacClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFacClienteMouseExited(evt);
            }
        });
        btFacCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacClienteActionPerformed(evt);
            }
        });
        jpFactura.add(btFacCliente, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 165, 45));

        jpUsuario.setBackground(new java.awt.Color(62, 169, 204));
        jpUsuario.setLayout(new java.awt.BorderLayout());

        btUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btUsuario.setText("Registrar Usuario");
        btUsuario.setBorder(null);
        btUsuario.setContentAreaFilled(false);
        btUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUsuarioMouseExited(evt);
            }
        });
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        jpUsuario.add(btUsuario, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 165, 45));

        jpProductos.setBackground(new java.awt.Color(62, 169, 204));
        jpProductos.setLayout(new java.awt.BorderLayout());

        btProductos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btProductos.setForeground(new java.awt.Color(255, 255, 255));
        btProductos.setText("Registrar Productos");
        btProductos.setBorder(null);
        btProductos.setContentAreaFilled(false);
        btProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProductosMouseExited(evt);
            }
        });
        btProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductosActionPerformed(evt);
            }
        });
        jpProductos.add(btProductos, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 165, 45));

        jpProveedor.setBackground(new java.awt.Color(62, 169, 204));
        jpProveedor.setLayout(new java.awt.BorderLayout());

        btProveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btProveedor.setText("Factura de Proveedor");
        btProveedor.setBorder(null);
        btProveedor.setContentAreaFilled(false);
        btProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProveedorMouseExited(evt);
            }
        });
        btProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProveedorActionPerformed(evt);
            }
        });
        jpProveedor.add(btProveedor, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 165, 45));

        jpCategoria.setBackground(new java.awt.Color(62, 169, 204));
        jpCategoria.setLayout(new java.awt.BorderLayout());

        btCategoria.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btCategoria.setText("Agregar Categoría");
        btCategoria.setBorder(null);
        btCategoria.setContentAreaFilled(false);
        btCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCategoriaMouseExited(evt);
            }
        });
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });
        jpCategoria.add(btCategoria, java.awt.BorderLayout.CENTER);

        jpFondo.add(jpCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 165, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
       VentanaCliente vCliente = new VentanaCliente();
       this.cerrarVentana();
    }//GEN-LAST:event_btClienteActionPerformed

    private void btFacClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacClienteActionPerformed
        VentanaFactura vFactura = new VentanaFactura();
        this.cerrarVentana();
    }//GEN-LAST:event_btFacClienteActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        VentanaUsuario vUsuario = new VentanaUsuario();
        this.cerrarVentana();
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductosActionPerformed
        VentanaProducto vProductos = new VentanaProducto();
        this.cerrarVentana();
    }//GEN-LAST:event_btProductosActionPerformed

    private void btProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProveedorActionPerformed
        VentanaProveedor vProveedor = new VentanaProveedor();
        this.cerrarVentana();
    }//GEN-LAST:event_btProveedorActionPerformed

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        VentanaCategoria vCategoria = new VentanaCategoria();
        this.cerrarVentana();
    }//GEN-LAST:event_btCategoriaActionPerformed

    private void btClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseEntered
        this.jpRCliente.setBackground(btColorOscuro);
    }//GEN-LAST:event_btClienteMouseEntered

    private void btClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseExited
        this.jpRCliente.setBackground(btColor);
    }//GEN-LAST:event_btClienteMouseExited

    private void btUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarioMouseEntered
        this.jpUsuario.setBackground(btColorOscuro);
    }//GEN-LAST:event_btUsuarioMouseEntered

    private void btUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarioMouseExited
        this.jpUsuario.setBackground(btColor);
    }//GEN-LAST:event_btUsuarioMouseExited

    private void btFacClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFacClienteMouseEntered
        this.jpFactura.setBackground(btColorOscuro);
    }//GEN-LAST:event_btFacClienteMouseEntered

    private void btFacClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFacClienteMouseExited
        this.jpFactura.setBackground(btColor);
    }//GEN-LAST:event_btFacClienteMouseExited

    private void btProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProductosMouseEntered
        this.jpProductos.setBackground(btColorOscuro);
    }//GEN-LAST:event_btProductosMouseEntered

    private void btProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProductosMouseExited
        this.jpProductos.setBackground(btColor);
    }//GEN-LAST:event_btProductosMouseExited

    private void btProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProveedorMouseEntered
        this.jpProveedor.setBackground(btColorOscuro);
    }//GEN-LAST:event_btProveedorMouseEntered

    private void btProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProveedorMouseExited
        this.jpProveedor.setBackground(btColor);
    }//GEN-LAST:event_btProveedorMouseExited

    private void btCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCategoriaMouseEntered
        this.jpCategoria.setBackground(btColorOscuro);
    }//GEN-LAST:event_btCategoriaMouseEntered

    private void btCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCategoriaMouseExited
        this.jpCategoria.setBackground(btColor);
    }//GEN-LAST:event_btCategoriaMouseExited

   
    public void cerrarVentana(){
        this.dispose();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCategoria;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFacCliente;
    private javax.swing.JButton btProductos;
    private javax.swing.JButton btProveedor;
    private javax.swing.JButton btUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpCategoria;
    private javax.swing.JPanel jpFactura;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProveedor;
    private javax.swing.JPanel jpRCliente;
    private javax.swing.JPanel jpUsuario;
    // End of variables declaration//GEN-END:variables
}
