/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasRegistro;

import Controladores.ControladorUsuario;
import static VentanasRegistro.VentanaIngreso.titulo;
import static VentanasRegistro.Colores.btCeleste;
import static VentanasRegistro.Colores.btCelesteOscuro;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaUsuario extends javax.swing.JFrame{

    private Color colorTextoOriginal = new Color(167,216,232);
     private int xMouse, yMouse;
    private ControladorUsuario cUsuario = new ControladorUsuario();
    /**
     * Creates new form VentanaCategoria
     */
    public VentanaUsuario() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.lbTituloU.setText(titulo);
        this.pintar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpFondo = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpAgregarUsuario = new javax.swing.JPanel();
        btAgregarUusario = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmarContrasena = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jpMarcoU = new javax.swing.JPanel();
        jpSalirU = new javax.swing.JPanel();
        btSalirU = new javax.swing.JButton();
        jpRegresarU = new javax.swing.JPanel();
        btRegresarU = new javax.swing.JButton();
        lbTituloU = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpFondo.setBackground(new java.awt.Color(214, 122, 30));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 169, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Usuario");
        jpContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 360, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(167, 216, 232));
        txtUsuario.setText("Ingrese el numero de CI");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jpContenedor.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 280, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 169, 204));
        jLabel2.setText("Usuario");
        jpContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, -1));

        jSeparator1.setBackground(new java.awt.Color(61, 169, 204));
        jSeparator1.setForeground(new java.awt.Color(40, 110, 133));
        jSeparator1.setToolTipText("");
        jpContenedor.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, 10));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 169, 204));
        jLabel3.setText("Nombre");
        jpContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(167, 216, 232));
        txtNombre.setText("Ingrese el nombre del usuario");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        jpContenedor.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, -1));

        jSeparator2.setForeground(new java.awt.Color(40, 110, 133));
        jpContenedor.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 290, 10));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 169, 204));
        jLabel4.setText("Contraseña");
        jpContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        jSeparator3.setForeground(new java.awt.Color(40, 110, 133));
        jpContenedor.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 290, 10));

        jpAgregarUsuario.setBackground(new java.awt.Color(62, 169, 204));
        jpAgregarUsuario.setLayout(new java.awt.BorderLayout());

        btAgregarUusario.setForeground(new java.awt.Color(255, 255, 255));
        btAgregarUusario.setText("Agregar");
        btAgregarUusario.setBorder(null);
        btAgregarUusario.setContentAreaFilled(false);
        btAgregarUusario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgregarUusario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseExited(evt);
            }
        });
        btAgregarUusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUusarioActionPerformed(evt);
            }
        });
        jpAgregarUsuario.add(btAgregarUusario, java.awt.BorderLayout.CENTER);

        jpContenedor.add(jpAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 165, 45));

        txtContrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasena.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(167, 216, 232));
        txtContrasena.setText("************");
        txtContrasena.setBorder(null);
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContrasenaMousePressed(evt);
            }
        });
        jpContenedor.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(61, 169, 204));
        jLabel5.setText("Confirmar contraseña");
        jpContenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, -1));

        txtConfirmarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmarContrasena.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtConfirmarContrasena.setForeground(new java.awt.Color(167, 216, 232));
        txtConfirmarContrasena.setText("************");
        txtConfirmarContrasena.setBorder(null);
        txtConfirmarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtConfirmarContrasenaMousePressed(evt);
            }
        });
        jpContenedor.add(txtConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));

        jSeparator4.setForeground(new java.awt.Color(40, 110, 133));
        jpContenedor.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 290, 10));

        jpFondo.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 370, 450));

        jpMarcoU.setBackground(new java.awt.Color(255, 255, 255));
        jpMarcoU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpMarcoUMouseDragged(evt);
            }
        });
        jpMarcoU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpMarcoUMousePressed(evt);
            }
        });
        jpMarcoU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSalirU.setBackground(new java.awt.Color(255, 255, 255));
        jpSalirU.setLayout(new java.awt.BorderLayout());

        btSalirU.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btSalirU.setText("X");
        btSalirU.setContentAreaFilled(false);
        btSalirU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalirU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSalirUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSalirUMouseExited(evt);
            }
        });
        btSalirU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirUActionPerformed(evt);
            }
        });
        jpSalirU.add(btSalirU, java.awt.BorderLayout.CENTER);

        jpMarcoU.add(jpSalirU, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 50, 30));

        jpRegresarU.setBackground(new java.awt.Color(255, 255, 255));
        jpRegresarU.setLayout(new java.awt.BorderLayout());

        btRegresarU.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btRegresarU.setText("<");
        btRegresarU.setContentAreaFilled(false);
        btRegresarU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegresarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegresarUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegresarUMouseExited(evt);
            }
        });
        btRegresarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarUActionPerformed(evt);
            }
        });
        jpRegresarU.add(btRegresarU, java.awt.BorderLayout.CENTER);

        jpMarcoU.add(jpRegresarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        lbTituloU.setText("jLabel7");
        jpMarcoU.add(lbTituloU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 30));

        jpFondo.add(jpMarcoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    // ****************** PRESSED ****************
    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        this.restablecerTextos();
        if(this.txtUsuario.getText().equals("Ingrese el numero de CI")){
            this.txtUsuario.setText("");
            this.txtUsuario.setForeground(Colores.btCeleste);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMouseEntered

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        this.restablecerTextos();
        if(this.txtNombre.getText().equals("Ingrese el nombre del usuario")){
            this.txtNombre.setText("");
            this.txtNombre.setForeground(Colores.btCeleste);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMousePressed
        this.restablecerTextos();
        if(String.valueOf(this.txtContrasena.getPassword()).equals("************")){
            this.txtContrasena.setText("");
            this.txtContrasena.setForeground(Colores.btCeleste);
        }
    }//GEN-LAST:event_txtContrasenaMousePressed

    private void txtConfirmarContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfirmarContrasenaMousePressed
        this.restablecerTextos();
        if(String.valueOf(this.txtConfirmarContrasena.getPassword()).equals("************")){
            this.txtConfirmarContrasena.setText("");
            this.txtConfirmarContrasena.setForeground(Colores.btCeleste);
        }
    }//GEN-LAST:event_txtConfirmarContrasenaMousePressed

    private void btAgregarUusarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseEntered
        this.jpAgregarUsuario.setBackground(Colores.btCelesteOscuro);
    }//GEN-LAST:event_btAgregarUusarioMouseEntered

    private void btAgregarUusarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseExited
        this.jpAgregarUsuario.setBackground(Colores.btCeleste);
    }//GEN-LAST:event_btAgregarUusarioMouseExited

    private void btAgregarUusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUusarioActionPerformed
        this.cUsuario.setUsuario(this.txtUsuario.getText());  
        this.cUsuario.setNombre(this.txtNombre.getText());
        this.cUsuario.setContrasena(String.valueOf(this.txtContrasena.getPassword()));
        this.cUsuario.setConfirmaContrasena(String.valueOf(this.txtConfirmarContrasena.getPassword()));
        
        if (cUsuario.controladorUsuario()) {
            JOptionPane.showMessageDialog(null, "No ingreso el usuario!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.txtUsuario.setText("");
            this.restablecerTextos();
            return;
        }
        
        if (cUsuario.controladorNombre()) {
            JOptionPane.showMessageDialog(null, "No ingreso el nombre del usuario!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.txtNombre.setText("");
            this.restablecerTextos();
            return;
        }
        
        if (cUsuario.controladorConfirmarContrasena()) {
            JOptionPane.showMessageDialog(null, "No ingreso la confirmacion de la contraseña del usuario!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.txtConfirmarContrasena.setText("");
            this.restablecerTextos();
            return;
        }
        
        if (cUsuario.controladorContrasena()) {
            JOptionPane.showMessageDialog(null, "No ingreso la contraseña del usuario!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.txtContrasena.setText("");
            this.restablecerTextos();
            return;
        }
        
    }//GEN-LAST:event_btAgregarUusarioActionPerformed

    private void btSalirUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirUMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btSalirUMouseClicked

    private void btSalirUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirUMouseEntered
        this.jpSalirU.setBackground(Colores.btRojo);
        this.btSalirU.setForeground(Color.white);
    }//GEN-LAST:event_btSalirUMouseEntered

    private void btSalirUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirUMouseExited
        this.jpSalirU.setBackground(Color.white);
        this.btSalirU.setForeground(Colores.btTextoSalir);
    }//GEN-LAST:event_btSalirUMouseExited

    private void btRegresarUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarUMouseEntered
        this.jpRegresarU.setBackground(btCeleste);
        this.btRegresarU.setForeground(Color.white);
    }//GEN-LAST:event_btRegresarUMouseEntered

    private void btRegresarUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarUMouseExited
        this.jpRegresarU.setBackground(Color.white);
        this.btRegresarU.setForeground(Colores.btTextoSalir);
    }//GEN-LAST:event_btRegresarUMouseExited

    private void btRegresarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarUActionPerformed
        VentanaMenu vMenu = new VentanaMenu();
        this.cerrarVentana();
    }//GEN-LAST:event_btRegresarUActionPerformed

    private void jpMarcoUMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMarcoUMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpMarcoUMouseDragged

    private void jpMarcoUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMarcoUMousePressed
        this.xMouse = evt.getX();
        this.yMouse = evt.getY();
    }//GEN-LAST:event_jpMarcoUMousePressed

    private void btSalirUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirUActionPerformed

    private void btRegresarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegresarUMouseClicked

    
    // ***************** MÉTODOS *****************
    private void restablecerTextos(){
        if(this.txtUsuario.getText().isEmpty()){
            this.txtUsuario.setText("Ingrese el numero de CI");
            this.txtUsuario.setForeground(colorTextoOriginal);
        }
        if(this.txtNombre.getText().isEmpty()){
            this.txtNombre.setText("Ingrese el nombre del usuario");
            this.txtNombre.setForeground(colorTextoOriginal);
        }
        if(String.valueOf(this.txtContrasena.getPassword()).isEmpty()){            
            this.txtContrasena.setText("************");
            this.txtContrasena.setForeground(colorTextoOriginal);
        }
        if(String.valueOf(this.txtConfirmarContrasena.getPassword()).isEmpty()){
            this.txtConfirmarContrasena.setText("************");
            this.txtConfirmarContrasena.setForeground(colorTextoOriginal);
        }
    }
    private void pintar() {
        this.lbTituloU.setForeground(Colores.btTextoSalir);
        this.btSalirU.setForeground(Colores.btTextoSalir);
        this.btRegresarU.setForeground(Colores.btTextoSalir);
    }
    
    public void cerrarVentana(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarUusario;
    private javax.swing.JButton btRegresarU;
    private javax.swing.JButton btSalirU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpAgregarUsuario;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMarcoU;
    private javax.swing.JPanel jpRegresarU;
    private javax.swing.JPanel jpSalirU;
    private javax.swing.JLabel lbTituloU;
    private javax.swing.JPasswordField txtConfirmarContrasena;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
