/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasRegistro;

import Controladores.ControladorCategoria;
import static VentanasRegistro.VentanaIngreso.titulo;
import static VentanasRegistro.Colores.btCeleste;
import static VentanasRegistro.Colores.btCelesteOscuro;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaCategoria extends javax.swing.JFrame{

    private ControladorCategoria cCategoria = new ControladorCategoria();
    private int xMouse, yMouse;    
    
    public VentanaCategoria() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.lbTituloCat.setText(titulo);
        this.pintar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpAgregarUsuario = new javax.swing.JPanel();
        btAgregarUusario = new javax.swing.JButton();
        txtNombreCat = new javax.swing.JTextField();
        jpMarcoCat = new javax.swing.JPanel();
        jpSalirCat = new javax.swing.JPanel();
        btSalirCat = new javax.swing.JButton();
        jpRegresarCat = new javax.swing.JPanel();
        btRegresarCat = new javax.swing.JButton();
        lbTituloCat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpFondo.setBackground(new java.awt.Color(62, 169, 204));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Categoria");
        jpContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 370, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(163, 163, 163));
        jLabel3.setText("Nombre");
        jpContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        jpAgregarUsuario.setBackground(new java.awt.Color(62, 169, 204));
        jpAgregarUsuario.setLayout(new java.awt.BorderLayout());

        btAgregarUusario.setBackground(new java.awt.Color(62, 169, 204));
        btAgregarUusario.setForeground(new java.awt.Color(255, 255, 255));
        btAgregarUusario.setText("Agregar");
        btAgregarUusario.setBorder(null);
        btAgregarUusario.setContentAreaFilled(false);
        btAgregarUusario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgregarUusario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseExited(evt);
            }
        });
        btAgregarUusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUusarioActionPerformed(evt);
            }
        });
        jpAgregarUsuario.add(btAgregarUusario, java.awt.BorderLayout.CENTER);

        jpContenedor.add(jpAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 165, 45));

        txtNombreCat.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreCat.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCat.setText("Ingrese el nombre de la categoria");
        txtNombreCat.setBorder(null);
        txtNombreCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreCatMousePressed(evt);
            }
        });
        jpContenedor.add(txtNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 30));

        jpFondo.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, 270));

        jpMarcoCat.setBackground(new java.awt.Color(255, 255, 255));
        jpMarcoCat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpMarcoCatMouseDragged(evt);
            }
        });
        jpMarcoCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpMarcoCatMousePressed(evt);
            }
        });

        jpSalirCat.setBackground(new java.awt.Color(255, 255, 255));
        jpSalirCat.setLayout(new java.awt.BorderLayout());

        btSalirCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btSalirCat.setText("X");
        btSalirCat.setContentAreaFilled(false);
        btSalirCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalirCatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSalirCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSalirCatMouseExited(evt);
            }
        });
        btSalirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirCatActionPerformed(evt);
            }
        });
        jpSalirCat.add(btSalirCat, java.awt.BorderLayout.CENTER);

        jpRegresarCat.setBackground(new java.awt.Color(255, 255, 255));
        jpRegresarCat.setLayout(new java.awt.BorderLayout());

        btRegresarCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btRegresarCat.setText("<");
        btRegresarCat.setContentAreaFilled(false);
        btRegresarCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarCatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegresarCatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegresarCatMouseExited(evt);
            }
        });
        jpRegresarCat.add(btRegresarCat, java.awt.BorderLayout.CENTER);

        lbTituloCat.setText("jLabel2");

        javax.swing.GroupLayout jpMarcoCatLayout = new javax.swing.GroupLayout(jpMarcoCat);
        jpMarcoCat.setLayout(jpMarcoCatLayout);
        jpMarcoCatLayout.setHorizontalGroup(
            jpMarcoCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMarcoCatLayout.createSequentialGroup()
                .addComponent(jpRegresarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbTituloCat, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(jpSalirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpMarcoCatLayout.setVerticalGroup(
            jpMarcoCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMarcoCatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpMarcoCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSalirCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpRegresarCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTituloCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpFondo.add(jpMarcoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        getContentPane().add(jpFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 405));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCatMousePressed
        this.txtNombreCat.setText("");
    }//GEN-LAST:event_txtNombreCatMousePressed

    private void btAgregarUusarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseEntered
        this.jpAgregarUsuario.setBackground(Colores.btCelesteOscuro);
    }//GEN-LAST:event_btAgregarUusarioMouseEntered

    private void btAgregarUusarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseExited
        this.jpAgregarUsuario.setBackground(Colores.btCeleste);
    }//GEN-LAST:event_btAgregarUusarioMouseExited

    private void btAgregarUusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUusarioActionPerformed
        this.cCategoria.setNombre(String.valueOf(this.txtNombreCat.getText()));
        
        if(this.cCategoria.controladorNombre()){
            JOptionPane.showMessageDialog(null,"No ha ingresado el usuario!","Error",JOptionPane.ERROR_MESSAGE);
            this.txtNombreCat.setFocusable(true);
            return;
        }
        
        JOptionPane.showMessageDialog(null,"Se ha registrado");
        this.txtNombreCat.setText("Ingrese el nombre de la categoria");        
    }//GEN-LAST:event_btAgregarUusarioActionPerformed

    private void btSalirCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirCatMouseEntered
        this.jpSalirCat.setBackground(Colores.btRojo);
        this.btSalirCat.setForeground(Color.white);
    }//GEN-LAST:event_btSalirCatMouseEntered

    private void btSalirCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirCatMouseExited
        this.jpSalirCat.setBackground(Color.white);
        this.btSalirCat.setForeground(Colores.btTextoSalir);        
    }//GEN-LAST:event_btSalirCatMouseExited

    private void btSalirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirCatActionPerformed

    private void btRegresarCatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarCatMouseEntered
        this.jpRegresarCat.setBackground(btCeleste);
        this.btRegresarCat.setForeground(Color.white);
    }//GEN-LAST:event_btRegresarCatMouseEntered

    private void btSalirCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalirCatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btSalirCatMouseClicked

    private void btRegresarCatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarCatMouseExited
        this.jpRegresarCat.setBackground(Color.white);
        this.btRegresarCat.setForeground(Colores.btTextoSalir);
    }//GEN-LAST:event_btRegresarCatMouseExited

    private void jpMarcoCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMarcoCatMousePressed
        this.xMouse = evt.getX();
        this.yMouse = evt.getY();
    }//GEN-LAST:event_jpMarcoCatMousePressed

    private void jpMarcoCatMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMarcoCatMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jpMarcoCatMouseDragged

    private void btRegresarCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarCatMouseClicked
        VentanaMenu vMenu = new VentanaMenu();
        this.cerrarVentana();
    }//GEN-LAST:event_btRegresarCatMouseClicked

    private void pintar(){
        this.btSalirCat.setForeground(Colores.btTextoSalir);
        this.btRegresarCat.setForeground(Colores.btTextoSalir);
        this.lbTituloCat.setForeground(Colores.btTextoSalir);
    }
    
    public void cerrarVentana(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarUusario;
    private javax.swing.JButton btRegresarCat;
    private javax.swing.JButton btSalirCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpAgregarUsuario;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpMarcoCat;
    private javax.swing.JPanel jpRegresarCat;
    private javax.swing.JPanel jpSalirCat;
    private javax.swing.JLabel lbTituloCat;
    private javax.swing.JTextField txtNombreCat;
    // End of variables declaration//GEN-END:variables
}
