/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasRegistro;

import Controladores.ControladorCategoria;
import static VentanasRegistro.VentanaIngreso.titulo;
import static VentanasRegistro.VentanaIngreso.btCeleste;
import static VentanasRegistro.VentanaIngreso.btCelesteOscuro;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VentanaCategoria extends javax.swing.JFrame{

    private ControladorCategoria cCategoria = new ControladorCategoria();
    /**
     * Creates new form VentanaCategoria
     */
    public VentanaCategoria() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpAgregarUsuario = new javax.swing.JPanel();
        btAgregarUusario = new javax.swing.JButton();
        txtNombreCat = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        miVolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpFondo.setBackground(new java.awt.Color(62, 169, 204));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Categoria");
        jpContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 370, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(163, 163, 163));
        jLabel3.setText("Nombre");
        jpContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, -1));

        jpAgregarUsuario.setBackground(new java.awt.Color(62, 169, 204));
        jpAgregarUsuario.setLayout(new java.awt.BorderLayout());

        btAgregarUusario.setBackground(new java.awt.Color(62, 169, 204));
        btAgregarUusario.setForeground(new java.awt.Color(255, 255, 255));
        btAgregarUusario.setText("Agregar");
        btAgregarUusario.setBorder(null);
        btAgregarUusario.setContentAreaFilled(false);
        btAgregarUusario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgregarUusario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAgregarUusarioMouseExited(evt);
            }
        });
        btAgregarUusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarUusarioActionPerformed(evt);
            }
        });
        jpAgregarUsuario.add(btAgregarUusario, java.awt.BorderLayout.CENTER);

        jpContenedor.add(jpAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 165, 45));

        txtNombreCat.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreCat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNombreCat.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCat.setText("Ingrese el nombre de la categoria");
        txtNombreCat.setBorder(null);
        txtNombreCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreCatMousePressed(evt);
            }
        });
        jpContenedor.add(txtNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 30));

        jpFondo.add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 370, 270));

        jMenu4.setText("Registrar");

        miVolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miVolver.setText("Volver");
        miVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVolverActionPerformed(evt);
            }
        });
        jMenu4.add(miVolver);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVolverActionPerformed
        VentanaMenu ventanaMenu = new VentanaMenu();
        this.cerrarVentana();
    }//GEN-LAST:event_miVolverActionPerformed

    private void txtNombreCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCatMousePressed
        this.txtNombreCat.setText("");
    }//GEN-LAST:event_txtNombreCatMousePressed

    private void btAgregarUusarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseEntered
        this.jpAgregarUsuario.setBackground(btCelesteOscuro);
    }//GEN-LAST:event_btAgregarUusarioMouseEntered

    private void btAgregarUusarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgregarUusarioMouseExited
        this.jpAgregarUsuario.setBackground(btCeleste);
    }//GEN-LAST:event_btAgregarUusarioMouseExited

    private void btAgregarUusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarUusarioActionPerformed
        this.cCategoria.setNombre(String.valueOf(this.txtNombreCat.getText()));
        
        if(this.cCategoria.controladorNombre()){
            JOptionPane.showMessageDialog(null,"No ha ingresado el usuario!","Error",JOptionPane.ERROR_MESSAGE);
            this.txtNombreCat.setFocusable(true);
            return;
        }
        
        JOptionPane.showMessageDialog(null,"Se ha registrado");
        this.txtNombreCat.setText("Ingrese el nombre de la categoria");        
    }//GEN-LAST:event_btAgregarUusarioActionPerformed

    public void cerrarVentana(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarUusario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpAgregarUsuario;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JMenuItem miVolver;
    private javax.swing.JTextField txtNombreCat;
    // End of variables declaration//GEN-END:variables
}
